name: Deploy Static Site to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: false # prevent caching the old bundler

    - name: Remove old bundler and install latest
      run: |
        gem uninstall bundler -a -x || true
        gem install bundler

    - name: Install dependencies with new Bundler
      run: bundle install

    - name: Deploy with Ruby script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: bundle exec ruby s3_setup.rb